services:
  passivbot:
    container_name: passivbot-manager-optimize
    image: passivbot-manager
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./passivbot/api-keys.json:/usr/src/passivbot/api-keys.json:ro
      - ./passivbot/configs:/usr/src/passivbot/configs
      - ./passivbot/data/backtests:/usr/src/passivbot/backtests
      - ./passivbot/cache/cache:/usr/src/passivbot/cache
      - ./passivbot/cache/caches:/usr/src/passivbot/caches
      - ./passivbot/cache/historical_data:/usr/src/passivbot/historical_data
      - ./passivbot/data/optimize_results:/usr/src/passivbot/optimize_results
      - ./passivbot/data/optimize_results_analysis:/usr/src/passivbot/optimize_results_analysis
    working_dir: /usr/src/passivbot
    #command: ["python", "src/optimize.py", "configs/bybit-multi-3.1.json"]

    # command:
    #   [
    #     "python",
    #     "src/tools/extract_best_config.py",
    #     "optimize_results/2024-11-24T15_04_27_414_coins_f5f5b7e0_all_results.txt",
    #     "-v",
    #   ]

    command: ["python", "src/backtest.py", "configs/bybit-multi-2.2.json"]

    # command:
    #   [
    #     "jupyter",
    #     "lab",
    #     "--allow-root",
    #     "--ip=0.0.0.0",
    #     "--no-browser",
    #     "--NotebookApp.token=''",
    #   ]
    # http://localhost:8888/lab
